export const countryCodes = [
  { code: "+44", name: "UK", shortName: "UK" },
  { code: "+1", name: "US", shortName: "US" },
  { code: "+1", name: "Canada", shortName: "CA" },
  { code: "+91", name: "India", shortName: "IN" },
  { code: "+61", name: "Australia", shortName: "AU" },
  { code: "+81", name: "Japan", shortName: "JP" },
  { code: "+49", name: "Germany", shortName: "DE" },
  { code: "+33", name: "France", shortName: "FR" },
  { code: "+39", name: "Italy", shortName: "IT" },
  { code: "+55", name: "Brazil", shortName: "BR" },
  { code: "+86", name: "China", shortName: "CN" },
  { code: "+7", name: "Russia", shortName: "RU" },
  { code: "+82", name: "South Korea", shortName: "KR" },
  { code: "+34", name: "Spain", shortName: "ES" },
  { code: "+351", name: "Portugal", shortName: "PT" },
  { code: "+46", name: "Sweden", shortName: "SE" },
  { code: "+47", name: "Norway", shortName: "NO" },
  { code: "+48", name: "Poland", shortName: "PL" },
  { code: "+52", name: "Mexico", shortName: "MX" },
  { code: "+31", name: "Netherlands", shortName: "NL" },
  { code: "+32", name: "Belgium", shortName: "BE" },
  { code: "+64", name: "New Zealand", shortName: "NZ" },
  { code: "+63", name: "Philippines", shortName: "PH" },
  { code: "+54", name: "Argentina", shortName: "AR" },
  { code: "+41", name: "Switzerland", shortName: "CH" },
  { code: "+30", name: "Greece", shortName: "GR" },
  { code: "+20", name: "Egypt", shortName: "EG" },
  { code: "+90", name: "Turkey", shortName: "TR" },
  { code: "+971", name: "UAE", shortName: "AE" },
  { code: "+66", name: "Thailand", shortName: "TH" },
  { code: "+62", name: "Indonesia", shortName: "ID" },
  { code: "+234", name: "Nigeria", shortName: "NG" },
  { code: "+27", name: "South Africa", shortName: "ZA" },
  { code: "+40", name: "Romania", shortName: "RO" },
  { code: "+45", name: "Denmark", shortName: "DK" },
  { code: "+371", name: "Latvia", shortName: "LV" },
  { code: "+370", name: "Lithuania", shortName: "LT" },
  { code: "+421", name: "Slovakia", shortName: "SK" },
  { code: "+386", name: "Slovenia", shortName: "SI" },
  { code: "+353", name: "Ireland", shortName: "IE" },
  { code: "+420", name: "Czech Republic", shortName: "CZ" },
  { code: "+994", name: "Azerbaijan", shortName: "AZ" },
  { code: "+373", name: "Moldova", shortName: "MD" },
  { code: "+374", name: "Armenia", shortName: "AM" },
  { code: "+880", name: "Bangladesh", shortName: "BD" },
  { code: "+965", name: "Kuwait", shortName: "KW" },
  { code: "+974", name: "Qatar", shortName: "QA" },
  { code: "+961", name: "Lebanon", shortName: "LB" },
  { code: "+60", name: "Malaysia", shortName: "MY" },
  { code: "+95", name: "Myanmar", shortName: "MM" },
  { code: "+213", name: "Algeria", shortName: "DZ" },
  { code: "+962", name: "Jordan", shortName: "JO" },
  { code: "+84", name: "Vietnam", shortName: "VN" },
  { code: "+92", name: "Pakistan", shortName: "PK" },
  { code: "+94", name: "Sri Lanka", shortName: "LK" },
  { code: "+93", name: "Afghanistan", shortName: "AF" },
  { code: "+968", name: "Oman", shortName: "OM" },
  { code: "+255", name: "Tanzania", shortName: "TZ" },
  { code: "+263", name: "Zimbabwe", shortName: "ZW" },
  { code: "+243", name: "DR Congo", shortName: "CD" },
  { code: "+260", name: "Zambia", shortName: "ZM" },
  { code: "+372", name: "Estonia", shortName: "EE" },
  { code: "+358", name: "Finland", shortName: "FI" },
  { code: "+237", name: "Cameroon", shortName: "CM" },
  { code: "+239", name: "Sao Tome & Principe", shortName: "ST" },
  { code: "+58", name: "Venezuela", shortName: "VE" },
  { code: "+595", name: "Paraguay", shortName: "PY" },
  { code: "+598", name: "Uruguay", shortName: "UY" },
  { code: "+389", name: "North Macedonia", shortName: "MK" },
  { code: "+268", name: "Eswatini", shortName: "SZ" },
  { code: "+290", name: "Saint Helena", shortName: "SH" },
  { code: "+975", name: "Bhutan", shortName: "BT" },
  { code: "+376", name: "Andorra", shortName: "AD" },
];
